### ISSUE TITLE
Failed to spawn command `phpcs`.

### ISSUE THREAD

**Issue by lukasoppermann** [bpearson/atom-phpcs#11]
Hey, I get the error:

```
Failed to spawn command `phpcs`. Make sure `phpcs` is installed and on your PATH
```

However I did install phpcs via composer https://github.com/squizlabs/PHP_CodeSniffer and I have composer in my `PATH` `export PATH="/usr/local/bin:/usr/local/sbin:~/.composer/vendor/bin:$PATH"`

This should be fine, correct? I still get the error though. Maybe it would be good if you could add the installation of phpcs to the readme. Thanks.

**Comment by lukasoppermann** [comment]
It somehow does not help I just get the same error message with the path:

```
Failed to spawn command `~/.composer/vendor/bin/phpcs`. Make sure `~/.composer/vendor/bin/phpcs` is installed and on your PATH
```

But when I run it from the cli it works fine. Maybe it can not access this? Is it possible that I have to do something so atom can access it?

**Comment by bpearson** [comment]
You got me. The only thing I can think of is maybe expand ~ to the full path? I know from experience some applications do not handle this.

**Comment by lukasoppermann** [comment]
If I do this I get an atom error `cannot open file`. Did you install phpcs via composer?

**Comment by bpearson** [comment]
na I still use PEAR.

**Comment by bpearson** [comment]
Just tried the composer way, by expanding the ~, seems to have it working. The cannot open file could be a problem with a config callback I have on that page. I can't look now, but I will file an issue and address it later. Try building the complete path outside and pasting it in, seems to workaround it.

**Comment by lukasoppermann** [comment]
Sadly it does not work for me either, are you on a mac as well? The expanded path would be `/Users/lukasoppermann/.composer/vendor/bin/phpcs` correct? I still get the `cannot open file` error.

Also all methods I tried with ~, expanded, just `phpcs` work fine in the cli-

**Comment by bpearson** [comment]
Nope, I'm on Linux. Yeah the error is fine, I think its because the setting registers a change and it tries to run phpcs on each editor open, so it should pop up cos it cannot open the file, but once its correct in the settings, the error should disappear. (To test it, once the setting is correct, go to an editor, make a cs violation and save (or ctrl-alt-s)). The path looks correct to me as well. Oh obviously assuming you did the composer global require command to install and not the package one. If none of that works, I got nothing :-(

**Comment by bpearson** [comment]
BTW the config setting issue is at https://github.com/bpearson/atom-phpcs/issues/12

**Comment by lukasoppermann** [comment]
Hmm, no I still can not get it to work. :(

**Comment by bpearson** [comment]
Not sure what is going on. I cannot replicate it here. You could try the new version which fixes the config bug, but I'm not holding my breath.

**Comment by lukasoppermann** [comment]
Hmm, no, sadly not, I still get the "incorrectly setup" option in the console. Can I provide any information? Could I have missed some setup step or something?

**Comment by bpearson** [comment]
This might explain the problem about the PATH https://github.com/rgbkrk/atom-script/issues/61,

But this doesn't address the issue of using the full path. In the CLI, did u try the full path and double check the full path. ie. if you try: /fullpath/to/phpcs --standard=STANDARD --report=csv /fullpath/to/file

Also what standard are you using? Is it a correct standard (check by phpcs -i)?

**Comment by lukasoppermann** [comment]
Okay, somehow it seems to now be working using the full path to both phpcs and phpcbf

```
/Users/lukasoppermann/.composer/vendor/bin/phpcbf
/Users/username/.composer/vendor/bin/phpcs
```

And the standard to `PSR2`.

I am a little bit confused, because it had it like this (apart from PSR1) before and it did not work. Maybe I restarted my mac in between and that fixed it. Works anyhow, thanks for your support. :+1:

**Comment by bpearson** [comment]
w00t!
