### ISSUE TITLE
Suggestion: run on save

### ISSUE THREAD

**Issue by lukasoppermann** [bpearson/atom-phpcs#13]
It would be nice to add an option to run the codesniffer on save.

**Comment by bpearson** [comment]
It does?

**Comment by lukasoppermann** [comment]
Ahh, true, it does not say so anywhere and if you have a line highlighted and hit save, you have to move to a different line and back to see the message at the bottom appear. (Just figured this out). 

Maybe you could state that it runs on save, just to make it obvious. :-)

**Comment by bpearson** [comment]
https://github.com/bpearson/atom-phpcs/issues/15

Docs are lacking (I'm terribad at writing docs), open to suggestions/PRs etc.
