### ISSUE TITLE
Add more info to readme.

### ISSUE THREAD

**Issue by lukasoppermann** [bpearson/atom-phpcs#14]
Hey, so I am still a bit confused how it is supposed to work, maybe you could add some screenshots, etc.

I saw that sometimes there is a message at the bottom of the screen. Will lines be marked as well? Maybe you could add an icon (warning and errors) with a count in the bottom bar? Or something like this? And maybe a "all fine" if no errors or warnings are available?

**Comment by bpearson** [comment]
Will add a screenie or two, but the gutter shows the errors/warning and when you move the cursor over a line with an error/warning, you get the message in the status bar

**Comment by lukasoppermann** [comment]
Ahha, okay, I also have a git plugin thingy, which does change the gutter as well and is on top of yours, so I actually did not get to see the markings from phpcs. :) 

I would still appreciate an (optional) counter in the status bar for people like me who use an interfering git packages.

**Comment by bpearson** [comment]
Can you post a screenie and which plugin? If I can replicate I will try and address it

**Comment by bpearson** [comment]
Done v1.3.0 but not entirely convinced moving it to the right was the way to go, but it will do for now (I tried having both on the left but red and yellow together was too much)

**Comment by lukasoppermann** [comment]
Well, I appreciate it, it definitely works. :+1:
