### ISSUE TITLE
Messages not readable.

### ISSUE THREAD

**Issue by lukasoppermann** [bpearson/atom-phpcs#16]
Currently many messages are cut off. I think you should facilitate all available space and definitely add a tooltip on hover. Thanks.

<img width="727" alt="screen shot 2015-11-18 at 09 04 59" src="https://cloud.githubusercontent.com/assets/813754/11235695/d889981c-8dd3-11e5-9b58-4a660044b192.png">

**Comment by bpearson** [comment]
Done v1.3.0
