### ISSUE TITLE
Uncaught TypeError: Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by roko79** [bpearson/atom-phpcs#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v1.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'messages' of undefined

```
At /Users/robertkovacs/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:185

TypeError: Cannot read property 'messages' of undefined
    at exit (/Users/robertkovacs/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:185:52)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
### Commands

```
     -8:50.4.0 tree-view:add-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -8:43.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:29.5.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -8:28.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -8:28.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -8:17.2.0 tree-view:add-folder (span.name.icon.icon-repo)
  4x -8:09.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:08.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:42.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -7:35.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:12.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:09.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-phpmd"
    ],
    "themes": [
      "northem-dark-atom-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-pair, v2.0.10 (active)
atom-phpcs, v1.4.0 (active)
emmet, v2.4.3 (active)
firewatch-syntax, v1.0.1 (inactive)
git-diff-details, v1.3.0 (active)
html-entities, v0.4.0 (active)
language-apache, v1.6.0 (active)
language-dots, v0.0.4 (active)
linter, v1.11.18 (active)
linter-markdown, v3.0.2 (active)
linter-php, v1.2.0 (active)
linter-phpcs, v1.4.1 (active)
linter-phpmd, v1.5.1 (inactive)
markdown-preview-plus, v2.4.0 (active)
northem-atom-syntax, v0.22.0 (inactive)
northem-atom-ui, v0.5.0 (inactive)
northem-dark-atom-syntax, v0.21.0 (inactive)
northem-dark-atom-ui, v0.5.0 (active)
php-analyser, v0.2.0 (active)
php-cs-fixer, v2.5.9 (active)
php-debug, v0.2.3 (active)
php-introspector, v1.0.0 (active)
sloc, v1.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by bpearson** [comment]
Not too sure how to replicate this, but did a small change which may help in version 1.4.1

**Comment by roko79** [comment]
Awesome, Thanks! 

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 5, 2016 at 17:31, Benjamin Pearson<notifications@github.com> wrote:   
Not too sure how to replicate this, but did a small change which may help in version 1.4.1

**Comment by bpearson** [comment]
Oh random thought, maybe phpcs is failing behind the scenes? Can you test the same file with the same standard you are using (eg. phpcs -i STANDARD --report=json /PATH/TO/FILE) ?

**Comment by roko79** [comment]
Unfortunately I cannot. I get this exception every time I use codecept. It happens since I downloaded the latest update. 
 Robert Kovacs
itsmycv@yahoo.com
1 (404) 909 0878
www.itsmycv.com 

    On Wednesday, October 5, 2016 5:41 PM, Benjamin Pearson <notifications@github.com> wrote:
 

 Oh random thought, maybe phpcs is failing behind the scenes? Can you test the same file with the same standard you are using (eg. phpcs -i STANDARD --report=json /PATH/TO/FILE) ?—

**Comment by roko79** [comment]
Sorry, actually I get it every time when I open a new file and there is an error inside... Maybe this can help you! Thanks! Robert Kovacs
itsmycv@yahoo.com
1 (404) 909 0878
www.itsmycv.com 

    On Wednesday, October 5, 2016 5:41 PM, Benjamin Pearson <notifications@github.com> wrote:
 

 Oh random thought, maybe phpcs is failing behind the scenes? Can you test the same file with the same standard you are using (eg. phpcs -i STANDARD --report=json /PATH/TO/FILE) ?—

**Comment by bpearson** [comment]
Na, still cannot replicate. Did u try version 1.4.1? Did that fix it?

**Comment by roko79** [comment]
Benjamin, sorry I finished my work hours yesterday and forgot to tell you, that 1.4.1 solved te problem!!! :)Thanks for your patience and help!

 Robert Kovacs
itsmycv@yahoo.com
1 (404) 909 0878
www.itsmycv.com 

    On Wednesday, October 5, 2016 6:44 PM, Benjamin Pearson <notifications@github.com> wrote:
 

 Na, still cannot replicate. Did u try version 1.4.1? Did that fix it?—

**Comment by kmcconnell** [comment]
I can confirm still happening in 1.4.1. I upgraded, restarted Atom, did not open any files, just went back to package settings to make sure it was upgraded, and these suckers showed up.

![screen shot 2016-10-06 at 3 30 41 pm](https://cloud.githubusercontent.com/assets/5774872/19167482/e65f0f80-8bd9-11e6-9fc0-4c0e8853f022.png)

... and that brought me here :)

**Comment by bpearson** [comment]
Weird, I don't see that at all. Can you show me the stack trace please?

**Comment by kmcconnell** [comment]
Yep, happening every few minutes with pretty much anything I do. Here's the stack traces from the latest couple.

`TypeError: Cannot read property 'messages' of undefined
    at exit (/Users/kanemcconnell/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:185:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`

`TypeError: Cannot read property 'messages' of undefined
    at exit (/Users/kanemcconnell/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:185:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`

**Comment by bpearson** [comment]
Not sure what is happening here, it works perfectly fine for me. What version of PHPCS are you using? Does it error out if you run it on the command line (phpcs --standard=PEAR --report=json FILE)? I just put a minor minor change in 1.4.2 to check the files array first before the messages array, but I think you might be having some problems with phpcs itself.

**Comment by bpearson** [comment]
Closed due to inactivity and unable to replicate. Please open a new issue if it still persists (the original issue was fixed on this report).
