### ISSUE TITLE
How to use a custom standard

### ISSUE THREAD

**Issue by pipo02mix** [bpearson/atom-phpcs#23]
I would like to know if it is possible to add a ruleset.xml and define its own rules.

**Comment by bpearson** [comment]
I have never tried it but it should be possible, just change the standard settings to the path of the ruleset.xml

**Comment by bpearson** [comment]
Actually, just tried, will figure out why it doesn't work

**Comment by bpearson** [comment]
Actually, my test was a fail ... I initially tried a standard that was part of phpcs, this failed due to some php fatal error about redeclaring class, I tried a totally custom standard not part of phpcs and it worked by passing the full path to the ruleset.xml.
