### ISSUE TITLE
Code sniffer runs for all file extensions

### ISSUE THREAD

**Issue by antbrown** [bpearson/atom-phpcs#25]
Hi,

On any open file, not ending in .php or .inc, for example README.md

The 1st line of the file will generate a Code Sniffer status bar message:

"No PHP was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them."

Not sure if I'm missing some setting, but had a quick look and thought that the path.match() test should test against a possible null return value.

I probably prematurely opened #24, it works for me, but then realised it may just be me this is happening to.

Cheers,
Ant

**Comment by bpearson** [comment]
I got it as well, not too sure why I didn't see it before (I am sure I did test that). The PR worked for me, let me know if this is still an issue. Closing this for now.

**Comment by antbrown** [comment]
So fast! Thanks. That was my first issue, first pull request and now first comment on GitHub :)

Have a great weekend!
