### ISSUE TITLE
Error parsing PHPCS response

### ISSUE THREAD

**Issue by andrii-maglovanyi** [bpearson/atom-phpcs#9]
Have error:
Something went wrong attempting to parse the PHPCS output.
when editing a php file according to Symfony2 standards, this is what i have using console version of phpcs:

phpcs --standard=Symfony2 src/AppBundle/Controller/IndexController.php 

FILE: .../src/AppBundle/Controller/IndexController.php
----------------------------------------------------------------------
FOUND 9 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
 10 | ERROR | [ ] Missing class doc comment
 12 | ERROR | [ ] Doc comment for parameter "$request" missing
 15 | ERROR | [ ] Missing @return tag in function comment
 21 | ERROR | [ ] Doc comment for parameter "$partials" missing
 21 | ERROR | [ ] Doc comment for parameter "$name" missing
 25 | ERROR | [ ] Missing @return tag in function comment
 26 | ERROR | [ ] Arguments with default values must be at the end of
    |       |     the argument list
 28 | ERROR | [x] Concat operator must not be surrounded by spaces
 29 | ERROR | [x] Multi-line function call not indented correctly;
    |       |     expected 8 spaces but found 12
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 457ms; Memory: 4Mb

**Comment by bpearson** [comment]
Assuming you are meaning it was not working on the current version? Please update it should be working again.
